### ISSUE TITLE
USAGE_PAGE out of spec

### ISSUE THREAD

**Issue by Rocky04** [WootingKb/wooting-analog-sdk-old#3]
The value of the define "WOOTING_ONE_ANALOG_USAGE_PAGE" are not in the valid range of FF00 - FFFF.

https://github.com/WootingKb/wooting-analog-sdk/blob/e27183fc4ce5d355eedf6fe540edccbe9fde83fd/src/wooting-analog-sdk.c#L12

**Comment by PastaJ36** [comment]
Changed to opening based on interface number. Usage page was not working on linux anyway.  a3d50795cd233354f4193426c5b7776ec5373911
